name: Mine Scala (XMRig Panthera)

on:
  workflow_dispatch:

jobs:
  mine:
    runs-on: ubuntu-latest
    name: Scala Mining Session
    steps:
    - name: Setup Mining
      run: |
        sudo apt update
        sudo apt install -y screen wget tar

    - name: Download XMRig Panthera
      run: |
        wget https://github.com/scala-network/official-miner/releases/download/v5.11.1/xmrig-panthera-linux.tar.gz
        tar -xvzf xmrig-panthera-linux.tar.gz
        chmod +x xmrig

    - name: Start Mining Scala
      run: |
        ./xmrig -o pool.scalaproject.io:2019 -u Ssy2SFtR3rGfjKFA4xxUnGVikpSy7GyfTFbDmjyqSGsuJMJ4K2GSKyK6pApbCy7DBGgf6b5p3fHwV1zHrnVRUjDG7kdm496A8R -p actions --donate-level 1 --coin scala --tls
